### ISSUE TITLE
Issues compiling on Windows

### ISSUE THREAD

**Issue by vd3d** [nonstd-lite/expected-lite#18] opened 2018-08-06 10:19 UTC
Hi,

I was using the version 0.0.2 and switched to 0.1.0 and I got a lot of compilation issues. I work with VS 2017. Noticed that I also use nonstd::optional !

It seems to have some conflicts !

Here is an extract of the errors I got :

c:\project\include\nonstd\expected.hpp(533): error C2011: 'nonstd::in_place_t': 'struct' type redefinition
c:\project\include\nonstd\optional.hpp(303): note: see declaration of 'nonstd::in_place_t'
c:\project\include\nonstd\expected.hpp(535): error C2079: 'in_place' uses undefined struct 'nonstd::in_place_t'
c:\project\include\nonstd\expected.hpp(535): error C2365: 'nonstd::in_place': redefinition; previous definition was 'function'

**Comment by martinmoene** [comment] 2018-08-06 14:11
Duplicate of issue #14.

Currently expected-lite and optional-lite do not go together with respect to in-place construction. I've tried to use the approach of optional-lite (and several other -lite) here, but ran into issues, which is one reason it's not yet fixed.

**Comment by martinmoene** [comment] 2018-09-16 07:42
Fixed via *nonstd-lite* [issue 17](https://github.com/martinmoene/nonstd-lite/issues/17): Align in_place between any, expected, optional, variant.

**Closed as completed by martinmoene** 2018-09-16 07:42 UTC
Labels: duplicate
